baseurl         = "https://randallmorey.github.io/recipe-book/"
theme           = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
canonifyurls    = true
publishDir      = "docs"

[params]
  title       = "Recipe Book"
  subtitle    = "Collected recipes"
  copyright   = ""

  cover       = ""
  description = ""
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  logo = ""
  orgName = "Recipes"
  orgWebsite = "https://randallmorey.github.io/recipe-book/"
  orgDescription = ""

  author = "Recipes"
  authorAvatar = ""
  authorLocation = ""
  authorWebsite = ""
  authorDescription = ""

  pageNotFoundTitle = "404 - Page not found"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Baking"
  url = "/categories/baking/"
  weight = 100

[[menu.main]]
  name = "Meals"
  url = "/categories/meals/"
  weight = 100
